version: '2.1'
orbs:
  ostorlab: ostorlab-circleci/ostorlab@1.2.1
workflows:
  use-my-orb:
    jobs:
      - ostorlab/ostorlab:
          ostorlab_api_key: 9Z4NI5bu.GgRi8YqhYSu4AZualZ0uA6wqGsEpXdZo
          asset_type: android-apk
          scan_profile: fast_scan
          scan_title: "Circleci: Scan without waiting for results"
          target: oxo_insecure.apk
